#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 29 18:07:01 2018

@author: ljknoll

testing evolution script for training web of neural networks

removed dependency on config.config_class
"""
import torch
import numpy as np
import matplotlib.pyplot as plt

from SkyNEt.modules.Nets.predNNet import predNNet
from SkyNEt.modules.Nets.webNNet import webNNet
import SkyNEt.experiments.boolean_logic.config_evolve_NN as config


cf = config.experiment_config()
cf.generations = 20
cf.mutationrate = 0.1
cf.fitnessavg = 1


# batch size
N = 10
# input data, size (N, 2*number of networks)
x = torch.linspace(-0.9, 0.9, N).repeat(2,1).t()
# target data, size (N)
target = np.linspace(0, 0.5, N)

# Initialize NN
main_dir = r'/home/lennart/Desktop/nnweb/'
data_dir = 'lr2e-4_eps400_mb512_20180807CP.pt'
net = predNNet(main_dir+data_dir)

web = webNNet()
web.add_vertex(net, 'A', output=True)
web.add_vertex(net, 'B')
web.add_arc('B', 'A', 3)

geneArray, outputArray, fitnessArray = web.trainGA(x, target, cf)

plt.figure()
plt.plot(-fitnessArray[:,0])

web.set_parameters_from_pool(geneArray[-1][0])
output_data = web.forward(x).detach().numpy()[:,0]
plt.figure()
plt.plot(output_data)
plt.plot(target)
plt.legend(['web output', 'target'])
