name: skynet
channels: 
 - defaults
 - conda-forge
dependencies:
 - h5py
 - matplotlib
 - pyqtgraph 
 - python=3.6
 - jsonschema
 - pyvisa
 - QtPy
 - sip
 - pyqt=5.6.0
 - numpy
 - scipy
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pytorch
